### ISSUE TITLE
Plasma without confirmations ("no-confs")

### ISSUE THREAD

**Issue by kasima** [omisego/research#21]

**Comment by smartcontracts** [comment]
# Background

Plasma currently requires that a transaction be "confirmed" by the sender before it's considered valid. This is due to data availability concerns (anti block withholding mechanism). More information is available in the resources below.

Note that the usage of "no-confs" here is different from the idea of zero-confirmation blockchain transactions.


# Research Questions:
- What problems are introduced when removing confirmations?
- Does removing confirmations create any useful side-effects?


# Resources
[Plasma w/o Confirmations](https://github.com/omisego/research/blob/master/plasma/plasma-mvp/specifications/no-confirmations.md)

**Comment by kasima** [comment]
This was addressed with [More Viable Plasma](https://github.com/omisego/elixir-omg/blob/master/docs/morevp.md)
