### ISSUE TITLE
Root chain congestion

### ISSUE THREAD

**Issue by kasima** [omisego/research#22]

**Comment by smartcontracts** [comment]
# Background

The current Minimal Viable Plasma design is vulnerable when the root chain is congested. This is basically due to the fact that users are required to exit within a timely manner or they risk losing their deposits. MVP specifies that users have one week to exit. 


# Research Questions
- How do we detect congestion on the root chain?
- Can we use the gas price to determine congestion?
- What short term solutions might solve this problem as we come up with better ways to deal with congestion?
- What realistic attacks can be accomplished via congestion?


# Resources
[Exploring `plasma-mvp`: Exit Priority](https://github.com/omisego/research/blob/master/plasma/plasma-mvp/explore/priority.md)
[Solidity: Units and Globally Available Variables](https://solidity.readthedocs.io/en/develop/units-and-global-variables.html#index-2)
