### ISSUE TITLE
Better reorg protection

### ISSUE THREAD

**Issue by kasima** [omisego/research#24]

**Comment by paulperegud** [comment]
What are the needs? ATM we are reorg-safe, at least in omisego/omisego.

**Comment by kasima** [comment]
@davidknott - could you elaborate here?

**Comment by DavidKnott** [comment]
@paulperegud We currently have reorg protection in that child chain block roots cannot unintentionally be submitted out of order.  That being said we're still relying on Ethereum for finality which we're currently basing on block confirmations.  If a reorg does happen all transactions on the child chain could be unrecorded on the root chain to reduce the damage of this situation I like the idea of (i) the operator being able to submit multiple blocks at a time or (ii) child chain block roots being able to be accepted asynchronously.

**Comment by paulperegud** [comment]
@DavidKnott from what angle are you analysing the situation? 

Operator's ability of producing correct chain is safe, since ATM operator just resubmits all the txes what are not yet in blocks.

Operator's ability to attempt to change blocks is there - but it is probabilistic (original txes are still in mempool of some nodes) and even operator succeeds, it will immediately be detected by every watcher. 

Do you want to improve finality of transfers on our child chain? Or are you worried about Ethereum congestion for block submission?

**Comment by boolafish** [comment]
@paulperegud I remember there's a gist doc for re-org protection. Could we move that doc to somewhere here or provide a link to there?

(BTW, I tried to search the link from slack but it's lost as the msg was deleted after time.)

**Comment by paulperegud** [comment]
https://gist.github.com/paulperegud/3fb4bb96693abe2e0b175f7b20e64362

**Comment by boolafish** [comment]
Thanks!

Closing this, as I created file to reference the link: https://github.com/omisego/research/blob/master/plasma/mechanical_reorg_protection.md

We can always re-open or create a separate issue if we want a deeper discussion on re-org.
