### ISSUE TITLE
Staking Pools

### ISSUE THREAD

**Issue by DavidKnott** [omisego/research#34]
Looking into how staking pools, particularly decentralized staking pools can operate.

**Comment by kfichter** [comment]
# Plasma MVP v. Plasma Cash Math

Corresponding spreadsheet [here](https://docs.google.com/spreadsheets/d/1olhdbTh0VarwUihhu7kgsTM_jNTqS4o4yeV4oh6OHQw/edit?usp=sharing).

## Plasma MVP

### Bits per Tx

$$
\text{bits per tx} = (\text{bits per utxo} + \text{bits per amount} + \text{bits per address} + \text{bits per signature}) * 4
$$

$$
= (57 + 256 + 160 + 520) * 4 = 3972
$$

### Bits per Block

$$
\text{bits per block} = \text{bits per tx} * \text{tx per block} = 3972 * \text{tx per block}
$$

### Total Bits

$$
\text{total bits} = \text{bits per block} * \text{total blocks}
$$

### Example

For 2^16 (65536) tx/block we have:

$$
\text{bits per block} = 3972 * 65536 = 260308992
$$

After 1 year, we have:

$$
\text{total bits} = 260308992 * 2103840 = 547648469729280
$$

Or ~68456 GB = ~68 TB per year.

## Plasma Cash

### Bits per Tx

**Note:** Proof size in bits decreases as the total number of watched coins increases because of caching at the higher tree levels. 

$$
\text{bits per tx} = (\text{tx size in bits}) + (\text{proof size in bits})
$$

$$
= (\text{bits per coin ID} + \text{bits per address} + \text{bits per signature}) + (\text{merkle depth} * \text{bits per hash})
$$

$$
= (25 + 160 + 520) + (\log_{2}(\frac{\text{total coins}}{\text{coins per watcher}}) * 256)
$$

$$
= 705 + \log_{2}(\frac{\text{total coins}}{\text{coins per watcher}}) * 256
$$

### Bits per Block

$$
\text{bits per block} = \text{bits per tx} * \text{coins per watcher}
$$

$$
= (705 + \log_{2}(\frac{\text{total coins}}{\text{coins per watcher}}) * 256) * \text{coins per watcher}
$$

### Blocks per Checkpoint

$$
\text{blocks per checkpoint} = \frac{\text{total coins}}{\text{coins per checkpoint}}
$$

### Total Bits

$$
\text{total bits} = \text{bits per block} * \text{blocks per checkpoint}
$$

### Example

For 2^24 (16777216) total coins and 10000 coins per watcher we have:

$$
\text{bits per block} = (705 + \log_{2}(\frac{16777216}{10000}) * 256) * 10000 = 34473456
$$

$$
\text{total bits} = 34473456 * 2048 = 70601638520
$$

Or ~9 GB.

**Comment by kartsims** [comment]
We have started a community effort to gather information about staking pools, in order to start our own community-driven pool (most of us are redditors) when network is up and running (on Plasma, not Tendermint), so I'll be watching this thread and would be happy to start a discussion
