### ISSUE TITLE
Privacy of deposits

### ISSUE THREAD

**Issue by paulperegud** [omisego/research#84]
We want deposits to be both secure and private - not leaking information about funds moving to the venue. 
* Security requirement - operator needs to be able to detect that input of the transaction is a deposit (so operator can forbid the spend). 
* Privacy requirement - nobody should know that output of this transaction is a deposit.
This two are in seeming conflict.

Solution - is as follows. We introduce additional possibility for the `owner` field of triple describing transaction output: `{owner, token, address}`. This field can contain:
* 20 bytes of the address of the owner;
* first 20 bytes of the hash of following string: `output_type || owner` (|| denotes concatenation).

Spends for the former case remains as they are now - signer needs to produce a signature which points to the owner. Spend for the latter now need also to reveal the preimage of the hash, revealing both real owner address and `output_type`.

This solution gives us ability to have deposits which are both private and secure. This technique can also be extended (in combination with snarks) to mask movement of funds on the venue.

--
EDIT: previous thinking on deposit/funding: https://github.com/omisego/research/issues/71

**Comment by paulperegud** [comment]
This technique enables https://github.com/omisego/research/issues/82 since it introduces clear way to separate full custody and restricted custody situations.

**Comment by boolafish** [comment]
One question bump into my mind, can the hashed value pass the address test? eg. `web3.utils.isAddress(...)`

If not, then it become obvious this tx is doing deposit. If yes....hmm then how do we differentiate in implementation.

An alternative is we change ownership value to be hashed by default. So even a truly normal output should use hash value to represent its ownership.

**Comment by paulperegud** [comment]
> One question bump into my mind, can the hashed value pass the address test? eg. `web3.utils.isAddress(...)`

Oh definitely. It is just a 20 bytes of random looking data.

> if yes....hmm then how do we differentiate in implementation.

Owner knows what type of owner field is this. He will create an appropriate variant of tx.

> An alternative is we change ownership value to be hashed by default

This solution is not free. It inflates tx size a bit when owner is a hash. Having every payment tx larger is not a negligible cost.

**Comment by boolafish** [comment]
1. yeah, just checked, last step of generating address is doing hash anyway so it's the same. I was thinking there might be some basic format on address.

1. I guess I was thinking sth different and not really a concern. BTW, I think the tx itself needs to has the flag that can only be known by user. (eg. encrypt the flag + nonce using its public key in metadata field). I think we want the user being able to restore all required data from his/her key only. Well... this means user should have the habit to put some random stuff on metadata field to make sure it won't get obvious.

1. ah....I mean we can always just take the first 20 bytes. But I was just concerning the result would look different from normal address vs this one. If they are the same there's no reason to do so.

**Comment by boolafish** [comment]
[NOTE]
I think we need `output_type || owner || nonce` instead of `output_type || owner` because this would only hide for the first time. Once used and revealed then that does not obfuscate anymore.

**Comment by boolafish** [comment]
btw, if we are using `nonce`, probably we don't need `output_type` at all (?)
however, not sure with or without is better

**Comment by paulperegud** [comment]
`nonce` is there just to randomize the masking address (otherwise it is deterministic - `H(known_constant, address_of_the_exchange)`).

`output_type` is a piece of data that informs contract and operator/watchers about the limitations on how the utxo can be spend.

**Comment by boolafish** [comment]
Ah, when I say `nonce` is enough, it is relying on the fact that we currently have only two possible use cases and there is no way to provide the signature for `...||nonce`. This already promises that only DEX tx can consume ownership with nonce. Not a good long term idea, of course.

---
okay, for a more generalized framework support, then I will need to clear my thought on possible implementation as this might not be as straight forward as it seems like:

Previously my thought on tx would look like:
```
tx: {
  type: xxx,
  inputs: [...],
  outputs:[{
    type: xxx,
    data: {
      ownership: xxxx,
      token: xxx,
      amount: xxx,
    },
  },...],
  witness: {},
  metaData: xxx,
}
```
And each tx type and output type would has its own model in solidity implementation, see [example here](https://github.com/boolafish/plasma-contracts/tree/asbtract_poc/abstract_poc/contracts/src/transactions/outputs).

Now, since we do not want `type` to be explicit inside output, so it would become something like:
```
tx: {
  type: xxx,
  inputs: [...],
  outputs:[{
    ownership: xxxx,
    token: xxx,
    amount: xxx,
  },...],
  witness: {},
  metaData: xxx,
}
```

Now, my question/issue would be:
1. where do we want to put `output type` on a normal payment transaction?
1. Since there is no such thing as "interface of struct" in solidity, so the two output types must share the same output model code actually.

For 1/
I guess we can only put `output type` in the same place: `ownership`. Meanwhile, I would like to propose a generalized function to check outputType to be with two inputs: `output_type`, and another `hash_data`. 

For instance it could be:
1. Payment transaction: ownership =  `output_type || hash(owner)`
1. Funding transaction: ownership = `output_type || hash(owner || exchange || nonce)` (<-- btw, I think it is better to explicit both owner & exchange. Without explicit exchange, user can double spend on different venues)

For 2/
Not a big deal, just previously it was one to one mapping from output model to output type, so we can just hard code things related to certain type. Also, it is really clear what type a model code stands. Now we have to write functions with input inserting the corresponding type.

**Comment by boolafish** [comment]
anyway, close this as the idea itself is clear and this issue is already linked in [Bonchan result doc](https://omisego.atlassian.net/wiki/spaces/RES/pages/41582752/Bonchon+cycle+%282019.03.27~2019.05.07%29+Research+Team+Progress?atlOrigin=eyJpIjoiNjY1NzU4M2M1YmY5NDFmNmFkZTNlYmY2ZjY0ZWU1ODMiLCJwIjoiYyJ9)
